# Generated by Django 5.0.6 on 2024-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('series', models.CharField(choices=[('8600', '8600'), ('9860', '9860')], max_length=4)),
                ('card_type', models.CharField(choices=[('uzcard', 'Uzcard'), ('humo', 'Humo')], editable=False, max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_year', models.PositiveIntegerField()),
                ('expiry_month', models.PositiveIntegerField()),
            ],
        ),
    ]
